Repository WildCodeSchool/202302-orleans-php-project-inovin, pull requests merged in 2023-06, with the labels that each got.

#2 initialisation du projet symfony
  assets/app.js
  assets/fonts/Fontspring-DEMO-theseasons-reg.otf
  assets/fonts/SnellBT-Regular.otf
  assets/images/LOGO_WILD_CODE_SCHOOL.png
  assets/images/favicon.svg
  assets/styles/_wcs.scss
  assets/styles/app.scss
  assets/styles/variables.scss
  config/routes.yaml
  package.json
  templates/admin.html.twig
  templates/base.html.twig
  templates/home/index.html.twig
  templates/visitor.html.twig
  yarn.lock
Labels: CHANGES REQUESTED

#3 livraison navbar
  assets/images/logo.svg
  assets/styles/app.scss
  assets/styles/svg.scss
  assets/styles/variables.scss
  src/Controller/HomeController.php
  templates/components/_navbar.html.twig
  templates/components/svg/_icon_person.html.twig
  templates/visitor.html.twig
Labels: REVIEWED

#4 created footer
  assets/images/facebook.svg
  assets/images/instagram.svg
  assets/images/line.svg
  assets/images/twitter.svg
  assets/images/youtube.svg
  assets/styles/_footer.scss
  assets/styles/app.scss
  assets/styles/variables.scss
  composer.json
  composer.lock
  templates/base.html.twig
  templates/components/_footer.html.twig
Labels: CONFLICTS RESOLVED, REVIEWED

#8 Fix navabar div missing
  templates/components/_navbar.html.twig
Labels: REVIEWED

#5 fin list cepage admin
  assets/styles/_fonts.scss
  assets/styles/_theme.scss
  assets/styles/_variables.scss
  assets/styles/admin.scss
  assets/styles/app.scss
  composer.json
  composer.lock
  config/packages/twig.yaml
  config/services.yaml
  migrations/Version20230606135433.php
  src/Controller/GrapeVarietyController.php
  src/DataFixtures/GrapeVarietyFixtures.php
  src/Entity/GrapeVariety.php
  src/Form/GrapeVarietyType.php
  src/Repository/GrapeVarietyRepository.php
  templates/admin.html.twig
  templates/components/svg_img/_frame_separator_svg
  templates/grape_variety/_delete_form.html.twig
  templates/grape_variety/_form.html.twig
  templates/grape_variety/edit.html.twig
  templates/grape_variety/index.html.twig
  templates/grape_variety/new.html.twig
  templates/grape_variety/show.html.twig
  templates/visitor.html.twig
  webpack.config.js
Labels: CONFLICTS RESOLVED, REVIEWED

#10 fix layout admin
  templates/admin.html.twig
Labels: REVIEWED

#11 fix navbar dropdown style
  assets/styles/_variables.scss
Labels: REVIEWED

#6 Us01 s02 contact form
  assets/styles/_variables.scss
  assets/styles/app.scss
  assets/styles/contactForm.scss
  config/packages/mailer.yaml
  config/services.yaml
  src/Controller/ContactController.php
  src/Entity/Contact.php
  src/Form/ContactFormType.php
  templates/base.html.twig
  templates/contact/_svg.html.twig
  templates/contact/contact.html.twig
  templates/contact/emailContact.html.twig
  templates/emailLayout.html.twig
  webpack.config.js
Labels: REVIEWED

#15 fixe request
  src/Controller/AdminHomeController.php
  templates/admin.html.twig
  templates/admin/components/_admin-navbar.html.twig
  templates/admin/index.html.twig
Labels: REVIEWED

#16 fix href
  templates/components/_navbar.html.twig
Labels: REVIEWED

#13 S01 us04 home
  assets/images/background-header.webp
  assets/images/pine-circle.png
  assets/images/vine.webp
  assets/styles/app.scss
  assets/styles/home.scss
  templates/components/_pine-circle.html.twig
  templates/home/index.html.twig
  templates/icones/decoration.svg
  templates/icones/surlignage.svg
  templates/icones/surlignage_main.svg
  webpack.config.js
Labels: REVIEWED

#18 fixe css
  assets/styles/app.scss
  assets/styles/home.scss
  templates/components/_footer.html.twig
  templates/components/_navbar.html.twig
  templates/components/svg/_icon_person.html.twig
  templates/home/index.html.twig
  templates/icones/decoration.svg
Labels: CONFLICTS RESOLVED, REVIEWED

#22 Fixe svg
  assets/styles/app.scss
  templates/home/index.html.twig
  templates/icones/surlignage_main.svg
Labels: REVIEWED

#25 add icon button
  assets/styles/app.scss
  templates/home/index.html.twig
  templates/icones/next.svg
Labels: REVIEWED

#26 fix contact form bg and title
  .env
  assets/styles/contactForm.scss
  templates/contact/contact.html.twig
Labels: REVIEWED

#27 livraisonn edit cépage
  src/Controller/GrapeVarietyController.php
  templates/components/svg_img/_icon_backlink.svg.twig
  templates/components/svg_img/_icon_edit.svg.twig
  templates/components/svg_img/_icon_validate.svg.twig
  templates/grape_variety/_form.html.twig
  templates/grape_variety/edit.html.twig
Labels: REVIEWED

#28 livraison cépage delete
  templates/components/svg_img/_icon_trash.svg.twig
  templates/grape_variety/_delete_form.html.twig
  templates/grape_variety/index.html.twig
Labels: REVIEWED

#29 add GrapeColor entity and link with GrapeVariety entity
  migrations/Version20230612205831.php
  migrations/Version20230612210211.php
  src/DataFixtures/GrapeColorFixtures.php
  src/DataFixtures/GrapeVarietyFixtures.php
  src/Entity/GrapeColor.php
  src/Entity/GrapeVariety.php
  src/Repository/GrapeColorRepository.php
Labels: REVIEWED

#23 Admin vin index
  migrations/Version20230613150910.php
  src/Controller/WineController.php
  src/DataFixtures/WineFixtures.php
  src/Entity/GrapeVariety.php
  src/Entity/Wine.php
  src/Form/WineType.php
  src/Repository/WineRepository.php
  templates/wine/_delete_form.html.twig
  templates/wine/_form.html.twig
  templates/wine/edit.html.twig
  templates/wine/index.html.twig
  templates/wine/new.html.twig
Labels: CONFLICTS RESOLVED, REVIEWED

#33 fix wine fixture
  src/DataFixtures/WineFixtures.php
Labels: REVIEWED

#32 fix add select color and link icon for grapeVariety template
  src/Form/GrapeVarietyType.php
  templates/components/svg_img/_icon_add.svg.twig
  templates/components/svg_img/_icon_backlink.svg.twig
  templates/components/svg_img/_icon_edit.svg.twig
  templates/components/svg_img/_icon_validate.svg.twig
  templates/grape_variety/index.html.twig
  templates/grape_variety/new.html.twig
Labels: REVIEWED

#30 S02 us44 user gestion
  assets/images/ornement.svg
  assets/styles/login.scss
  composer.json
  composer.lock
  config/packages/security.yaml
  migrations/Version20230613101713.php
  src/Controller/LoginController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  templates/components/_footer.html.twig
  templates/components/_navbar.html.twig
  templates/icones/surlignage.svg
  templates/login/index.html.twig
  webpack.config.js
Labels: REVIEWED

#17 S01 u13 sessions Read part of crud
  assets/images/corner-down-right.svg
  assets/images/corner-up-left.svg
  assets/images/corner.svg
  assets/styles/admin.scss
  migrations/Version20230608094805.php
  src/Controller/SessionController.php
  src/DataFixtures/SessionFixtures.php
  src/Entity/Session.php
  src/Form/SessionType.php
  src/Repository/SessionRepository.php
  templates/admin.html.twig
  templates/admin/components/_admin-navbar.html.twig
  templates/session/_delete_form.html.twig
  templates/session/_form.html.twig
  templates/session/edit.html.twig
  templates/session/index.html.twig
  templates/session/new.html.twig
  templates/session/show.html.twig
Labels: CONFLICTS RESOLVED, REVIEWED

#35 add logout
  config/packages/security.yaml
  config/routes.yaml
  templates/components/_navbar.html.twig
  templates/components/svg/_icon_logout.html.twig
  templates/components/svg/_icon_profile.html.twig
Labels: REVIEWED

#37 fix the svg name and add a path
  templates/admin/components/_admin-navbar.html.twig
Labels: REVIEWED

#34 fin style button link partie cepage
  assets/styles/app.scss
  templates/components/svg/_icon_profile.html.twig
  templates/components/svg_img/_icon_add.svg.twig
  templates/components/svg_img/_icon_backlink.svg.twig
  templates/components/svg_img/_icon_edit.svg.twig
  templates/components/svg_img/_icon_trash.svg.twig
  templates/components/svg_img/_icon_validate.svg.twig
  templates/grape_variety/_delete_form.html.twig
  templates/grape_variety/_form.html.twig
  templates/grape_variety/index.html.twig
  templates/grape_variety/new.html.twig
Labels: CONFLICTS RESOLVED, REVIEWED

#38 ajout d'une zone description pour le cépage
  migrations/Version20230615085742.php
  src/DataFixtures/GrapeVarietyFixtures.php
  src/Entity/GrapeVariety.php
  src/Form/GrapeVarietyType.php
  templates/grape_variety/new.html.twig
Labels: REVIEWED

#36 wine add
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  config/services.yaml
  migrations/Version20230614140238.php
  src/Controller/WineController.php
  src/DataFixtures/WineFixtures.php
  src/Entity/Wine.php
  src/Form/WineType.php
  symfony.lock
  templates/wine/_form.html.twig
  templates/wine/new.html.twig
Labels: CONFLICTS RESOLVED, REVIEWED

#39 ajout des badge de couleurs
  assets/styles/_theme.scss
  src/Entity/GrapeColor.php
  templates/grape_variety/index.html.twig
Labels: REVIEWED

#40 fix version error
  migrations/Version20230615085742.php
Labels: AWAITING TEAM REVIEW

#41 edit Wine
  src/Controller/WineController.php
  templates/wine/_form.html.twig
  templates/wine/edit.html.twig
  templates/wine/index.html.twig
Labels: REVIEWED

#42 delete Wine
  templates/wine/_delete_form.html.twig
  templates/wine/index.html.twig
Labels: REVIEWED

#43 Session edit part of crud
  assets/styles/_variables.scss
  src/Form/SessionType.php
  templates/session/_form.html.twig
  templates/session/edit.html.twig
Labels: REVIEWED

#44 integration other data from entity
  src/Controller/AdminHomeController.php
  src/Entity/AdminDashboard.php
  src/Repository/AdminDashboardRepository.php
  src/Repository/GrapeVarietyRepository.php
  src/Repository/SessionRepository.php
  src/Repository/UserRepository.php
  src/Repository/WineRepository.php
  src/Service/AdminDashboardService.php
Labels: REVIEWED

#46 separation admin pour grape_variety
  src/Controller/admin/AdminGrapeVarietyController.php
  templates/admin/components/_admin-navbar.html.twig
  templates/admin/grape_variety/_delete_form.html.twig
  templates/admin/grape_variety/_form.html.twig
  templates/admin/grape_variety/edit.html.twig
  templates/admin/grape_variety/index.html.twig
  templates/admin/grape_variety/new.html.twig
  templates/admin/grape_variety/show.html.twig
Labels: REVIEWED

#48 rename and move svg to svg directory
  templates/admin/components/_admin-navbar.html.twig
  templates/components/_navbar.html.twig
  templates/components/svg/_frame_surlignage.svg.twig
  templates/components/svg/_frame_surlignage_main.svg.twig
  templates/components/svg/_icon_decoration.svg.twig
  templates/components/svg/_icon_logout.svg.twig
  templates/components/svg/_icon_next.svg.twig
  templates/components/svg/_icon_pine-circle.html.twig
  templates/components/svg/_icon_profile.svg.twig
  templates/contact/_svg.html.twig
  templates/home/index.html.twig
  templates/icones/decoration.svg
  templates/icones/surlignage_main.svg
Labels: REVIEWED

#47 refactorisation dossier svg_img et svg
  assets/images/corner-down-right.svg
  assets/images/corner-up-left.svg
  assets/images/corner.svg
  assets/styles/admin.scss
  templates/admin.html.twig
  templates/admin/grape_variety/_delete_form.html.twig
  templates/admin/grape_variety/_form.html.twig
  templates/admin/grape_variety/index.html.twig
  templates/admin/grape_variety/new.html.twig
  templates/components/svg/_frame_separator.svg.twig
  templates/components/svg/_icon_add.svg.twig
  templates/components/svg/_icon_backlink.svg.twig
  templates/components/svg/_icon_edit.svg.twig
  templates/components/svg/_icon_trash.svg.twig
  templates/components/svg/_icon_validate.svg.twig
  templates/contact/_svg.html.twig
  templates/contact/contact.html.twig
  templates/session/_delete_form.html.twig
  templates/session/_form.html.twig
  templates/session/index.html.twig
  templates/wine/_delete_form.html.twig
  templates/wine/_form.html.twig
  templates/wine/index.html.twig
  templates/wine/new.html.twig
Labels: CONFLICTS RESOLVED, REVIEWED

#49 us21_tastingSheet
  assets/images/bottleWine.jpg
  assets/styles/tastingSheet.scss
  migrations/Version20230615081440.php
  src/Controller/TastingSheetController.php
  src/DataFixtures/SessionFixtures.php
  src/Entity/Session.php
  src/Entity/Wine.php
  templates/tasting_sheet/index.html.twig
  webpack.config.js
Labels: CONFLICTS RESOLVED, REVIEWED

#52 fixe_footer
  assets/styles/_footer.scss
  assets/styles/app.scss
  templates/components/_footer.html.twig
  templates/components/_navbar.html.twig
Labels: REVIEWED

#53 fixe navbar
  templates/components/_navbar.html.twig
  templates/components/svg/_icon_profile.svg.twig
Labels: REVIEWED

#54 fixe-home
  assets/styles/home.scss
  templates/components/svg/_icon_decoration.svg.twig
  templates/home/index.html.twig
Labels: REVIEWED

#50 S02 us05 user register
  assets/styles/_footer.scss
  assets/styles/_variables.scss
  assets/styles/app.scss
  assets/styles/login.scss
  assets/styles/registration.scss
  composer.json
  composer.lock
  config/bundles.php
  migrations/Version20230617152808.php
  migrations/Version20230619200504.php
  src/Controller/RegistrationController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  src/Security/EmailVerifier.php
  symfony.lock
  templates/components/svg/_frame_vertical_line.svg
  templates/components/svg/_icon_close.svg.twig
  templates/components/svg/_icon_validate.svg.twig
  templates/home/index.html.twig
  templates/login/index.html.twig
  templates/registration/confirmation_email.html.twig
  templates/registration/register.html.twig
  webpack.config.js
Labels: CONFLICTS RESOLVED, REVIEWED

#55 fix double index
  migrations/Version20230615081440.php
Labels: REVIEWED

#56 fixe_footer_css
  assets/styles/_footer.scss
  templates/components/_footer.html.twig
Labels: REVIEWED

#57 fixe_svg
  templates/login/index.html.twig
Labels: REVIEWED

#58 moved session to admin folder and fixed checkbox in formtype
  composer.lock
  src/Controller/SessionController.php
  src/Form/SessionType.php
  templates/admin/components/_admin-navbar.html.twig
  templates/admin/session/_delete_form.html.twig
  templates/admin/session/_form.html.twig
  templates/admin/session/edit.html.twig
  templates/admin/session/index.html.twig
  templates/admin/session/new.html.twig
  templates/admin/session/show.html.twig
Labels: REVIEWED

#59 fix image path
  templates/admin/grape_variety/_form.html.twig
  templates/admin/grape_variety/index.html.twig
  templates/admin/grape_variety/new.html.twig
  templates/components/_navbar.html.twig
  templates/components/svg/_frame_vertical_line.svg.twig
  templates/registration/register.html.twig
  templates/visitor.html.twig
Labels: REVIEWED

#60 fixe_css_contact
  assets/styles/contactForm.scss
  src/Form/ContactFormType.php
  templates/contact/contact.html.twig
Labels: REVIEWED

#51 S3 u19 show opened session
  assets/images/img_card_wine.svg
  assets/styles/_footer.scss
  assets/styles/_variables.scss
  assets/styles/app.scss
  assets/styles/session.scss
  composer.json
  composer.lock
  src/Controller/SessionController.php
  templates/admin/session/sessions_states_html.twig
  templates/components/_navbar.html.twig
  templates/components/session/_card_session_grape_variety.html.twig
  templates/components/session/_opened_sessions.html.twig
  templates/components/svg/_frame_surlignage_main.svg.twig
  templates/components/svg/_icon_eye.svg.twig
  webpack.config.js
Labels: CONFLICTS RESOLVED, REVIEWED

#62 added style to add page
  templates/admin/session/new.html.twig
Labels: REVIEWED

#63 fixed missing text part on homepage
  templates/home/index.html.twig
Labels: REVIEWED

#64 fix missing folder
  composer.lock
  templates/session/sessions_states_html.twig
Labels: REVIEWED

#65 fixed delete function inside crud section
  templates/admin/session/_delete_form.html.twig
Labels: REVIEWED

#66 added flash messages to session management
  src/Controller/SessionController.php
  templates/admin/session/_delete_form.html.twig
Labels: CORRECTIONS DONE, REVIEWED

#67 done my tastingSheet
  assets/images/img_card_wine.svg
  assets/styles/_footer.scss
  assets/styles/_variables.scss
  assets/styles/app.scss
  assets/styles/contactForm.scss
  assets/styles/login.scss
  assets/styles/registration.scss
  assets/styles/session.scss
  assets/styles/tastingSheet.scss
  composer.json
  composer.lock
  config/bundles.php
  migrations/Version20230617152808.php
  migrations/Version20230619200504.php
  src/Controller/RegistrationController.php
  src/Controller/SessionController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Form/ContactFormType.php
  src/Form/RegistrationFormType.php
  src/Form/SessionType.php
  src/Security/EmailVerifier.php
  symfony.lock
  templates/admin/components/_admin-navbar.html.twig
  templates/admin/grape_variety/_form.html.twig
  templates/admin/grape_variety/index.html.twig
  templates/admin/grape_variety/new.html.twig
  templates/admin/session/_delete_form.html.twig
  templates/admin/session/edit.html.twig
  templates/components/_footer.html.twig
  templates/components/_navbar.html.twig
  templates/components/session/_card_session_grape_variety.html.twig
  templates/components/session/_opened_sessions.html.twig
  templates/components/svg/_frame_surlignage_main.svg.twig
  templates/components/svg/_frame_vertical_line.svg.twig
  templates/components/svg/_icon_close.svg.twig
  templates/components/svg/_icon_eye.svg.twig
  templates/components/svg/_icon_validate.svg.twig
  templates/contact/contact.html.twig
  templates/home/index.html.twig
  templates/login/index.html.twig
  templates/registration/confirmation_email.html.twig
  templates/registration/register.html.twig
  templates/session/_delete_form.html.twig
  templates/session/_form.html.twig
  templates/session/edit.html.twig
  templates/session/index.html.twig
  templates/session/new.html.twig
  templates/session/sessions_states_html.twig
  templates/session/show.html.twig
  templates/tasting_sheet/index.html.twig
  templates/visitor.html.twig
  webpack.config.js
Labels: CONFLICTS RESOLVED, REVIEWED

#68 fin card liste des vins pour les visiteurs
  assets/app.js
  assets/images/line_bolder.svg
  assets/images/placeholder_wine.jpg
  assets/styles/app.scss
  assets/styles/wine.scss
  migrations/Version20230621125326.php
  package.json
  src/Controller/WineController.php
  src/Controller/admin/AdminWineController.php
  src/DataFixtures/WineFixtures.php
  src/Entity/Wine.php
  templates/admin/components/_admin-navbar.html.twig
  templates/admin/wine/_delete_form.html.twig
  templates/admin/wine/_form.html.twig
  templates/admin/wine/edit.html.twig
  templates/admin/wine/index.html.twig
  templates/admin/wine/new.html.twig
  templates/components/_navbar.html.twig
  templates/components/session/_opened_sessions.html.twig
  templates/components/svg/_icon_cart_check_fill.svg.twig
  templates/login/index.html.twig
  templates/wine/index.html.twig
  webpack.config.js
  yarn.lock
Labels: CONFLICTS RESOLVED, REVIEWED

#70 ajout du choix de vins dans la partie admin des seances
  assets/styles/admin.scss
  src/Entity/Wine.php
  src/Form/SessionType.php
Labels: CONFLICTS RESOLVED, REVIEWED

#78 fix controller admin session route
  src/Controller/admin/AdminSessionController.php
Labels: REVIEWED

#69 S03 us49 password
  assets/styles/app.scss
  assets/styles/resetPassword.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/reset_password.yaml
  migrations/Version20230621121448.php
  src/Controller/ResetPasswordController.php
  src/Entity/ResetPasswordRequest.php
  src/Form/ChangePasswordFormType.php
  src/Form/ResetPasswordRequestFormType.php
  src/Repository/ResetPasswordRequestRepository.php
  symfony.lock
  templates/components/svg/_icon_info.svg.twig
  templates/components/svg/_icon_next.svg.twig
  templates/login/index.html.twig
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
  webpack.config.js
Labels: CONFLICTS RESOLVED, REVIEWED

#81 fixe webpack
  webpack.config.js
Labels: REVIEWED

#83 fix color opening session
  assets/styles/_theme.scss
  assets/styles/_variables.scss
  templates/components/session/_opened_sessions.html.twig
Labels: REVIEWED

#84 fix rate alcool and style price card
  assets/styles/wine.scss
  templates/wine/index.html.twig
Labels: REVIEWED

#85 suppression du message de connexion sur vins et seanecs
  templates/components/session/_opened_sessions.html.twig
  templates/wine/index.html.twig
Labels: REVIEWED

#87 Fix style date session
  assets/styles/admin.scss
  src/Controller/SessionController.php
  src/Form/SessionType.php
  templates/admin/session/_form.html.twig
Labels: REVIEWED

#88 change color of icon description
  templates/components/session/_opened_sessions.html.twig
Labels: REVIEWED

#89 Fix database
  src/Entity/Session.php
  src/Entity/Wine.php
Labels: REVIEWED

#82 S3 u53 filter wine on index page
  assets/app.js
  assets/styles/app.scss
  assets/styles/wine.scss
  assets/wine.js
  package-lock.json
  package.json
  src/Controller/WineController.php
  src/Form/Search/SearchWineDataFormType.php
  src/Repository/WineRepository.php
  src/Search/SearchWineData.php
  templates/components/search/_searchWinFormData.html.twig
  templates/components/svg/_icon_search.svg.twig
  templates/wine/index.html.twig
  webpack.config.js
  yarn.lock
Labels: REVIEWED
