Repository WildCodeSchool/202302-orleans-php-project-inovin, pull requests merged in 2023-07, with the labels that each got.

#94 fix reset bug
  assets/wine.js
Labels: REVIEWED

#93 S4U50 Send Email For Wine Order
  assets/controllers.json
  assets/styles/wine.scss
  composer.json
  composer.lock
  config/bundles.php
  config/routes/ux_live_component.yaml
  package.json
  src/Service/SendOrderService.php
  src/Twig/Components/SendWineOrderComponent.php
  symfony.lock
  templates/components/SendWineOrderComponent.html.twig
  templates/wine/email/emailWineOrder.html.twig
  templates/wine/index.html.twig
  yarn.lock
Labels: CONFLICTS RESOLVED, REVIEWED

#92 delete recipe
  src/Controller/admin/AdminRecipeController.php
  templates/admin/admin_recipe/_delete_form.html.twig
  templates/admin/admin_recipe/_form.html.twig
  templates/admin/admin_recipe/edit.html.twig
  templates/admin/admin_recipe/index.html.twig
  templates/admin_recipe/_delete_form.html.twig
  templates/admin_recipe/new.html.twig
Labels: REVIEWED

#96 Registration stimulus
  composer.json
  composer.lock
  src/Controller/RegistrationController.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  src/Security/EmailVerifier.php
  src/Twig/Components/RegistrationForm.php
  templates/components/RegistrationForm.html.twig
  templates/registration/register.html.twig
Labels: CONFLICTS RESOLVED, REVIEWED

#97 fix query opened session
  src/Controller/SessionController.php
  src/DataFixtures/SessionFixtures.php
  src/Repository/SessionRepository.php
  templates/components/session/_card_session.html.twig
  templates/components/session/_next_sessions.html.twig
  templates/components/session/_opened_sessions.html.twig
  templates/session/sessions_states_html.twig
Labels: REVIEWED

#98 add turbo symfony ux to sit web
  assets/controllers.json
  composer.json
  composer.lock
  config/bundles.php
  package.json
  symfony.lock
  templates/components/search/_searchWinFormData.html.twig
  yarn.lock
Labels: REVIEWED

#99 fixe security route + navbar
  assets/styles/app.scss
  config/packages/security.yaml
  templates/admin/components/_admin-navbar.html.twig
  templates/components/_navbar.html.twig
  templates/components/svg/_icon_deco.svg.twig
Labels: REVIEWED

#95 Us22 form tasting sheet
  composer.lock
  migrations/Version20230622151144.php
  migrations/Version20230623073728.php
  package.json
  src/Controller/TastingSheetController.php
  src/DataFixtures/RecipeFixtures.php
  src/DataFixtures/TastingSheetFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/TastingSheet.php
  src/Entity/Wine.php
  src/Form/RecipeTastingSheetType.php
  src/Form/RecipeType.php
  src/Form/TastingSheetType.php
  templates/tasting_sheet/index.html.twig
  yarn.lock
Labels: CONFLICTS RESOLVED, REVIEWED

#102 fin favorite wine
  assets/styles/_theme.scss
  migrations/Version20230704131455.php
  src/DataFixtures/WineFixtures.php
  src/Entity/User.php
  src/Entity/Wine.php
  src/Twig/Components/UpdateStateFavoriteWineComponent.php
  templates/components/UpdateStateFavoriteWineComponent.html.twig
  templates/components/svg/_icon_heart.svg.twig
  templates/components/svg/_icon_heart_fill.svg.twig
  templates/wine/index.html.twig
Labels: REVIEWED

#104 fix turbo relaod script
  config/packages/webpack_encore.yaml
Labels: REVIEWED

#86 S03 us52 resultats fiches
  assets/styles/result-tastingsheet.scss
  src/Controller/TastingSheetController.php
  src/DataFixtures/TastingSheetFixtures.php
  src/Entity/Recipe.php
  src/Entity/TastingSheet.php
  src/Form/UserType.php
  templates/admin/user/_delete_form.html.twig
  templates/admin/user/_form.html.twig
  templates/admin/user/edit.html.twig
  templates/admin/user/new.html.twig
  templates/components/svg/_icon_clock.svg.twig
  templates/components/svg/_icon_date.svg.twig
  templates/tasting_sheet/resultTastingSheet.html.twig
  webpack.config.js
Labels: REVIEWED

#107 fix seance start
  src/Controller/SessionController.php
  src/Controller/TastingSheetController.php
Labels: REVIEWED

#106 Fix degustation
  assets/styles/tastingSheet.scss
  src/Form/TastingSheetType.php
  templates/tasting_sheet/index.html.twig
Labels: CONFLICTS RESOLVED, REVIEWED

#103 error pages
  assets/images/error403.png
  assets/images/error404.png
  assets/images/error500.webp
  assets/styles/app.scss
  assets/styles/home.scss
  composer.lock
  templates/bundles/TwigBundle/Exception/error.html.twig
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
Labels: CONFLICTS RESOLVED, REVIEWED

#108 create recipe
  assets/styles/recipe.scss
  migrations/Version20230705145311.php
  src/Controller/RecipeController.php
  src/Entity/TastingSheet.php
  templates/components/svg/_icon_wine_ticket.svg.twig
  templates/recipe/index.html.twig
  webpack.config.js
Labels: REVIEWED

#101 S05 us55 display members
  assets/styles/_variables.scss
  assets/styles/admin.scss
  src/Controller/admin/AdminUserController.php
  src/DataFixtures/UserFixtures.php
  templates/admin.html.twig
  templates/admin/components/_admin-navbar.html.twig
  templates/admin/user/edit.html.twig
  templates/admin/user/index.html.twig
  templates/admin/user/show.html.twig
Labels: REVIEWED

#109 S5 u60 favorites recipe
  migrations/Version20230706061855.php
  src/Entity/Recipe.php
  src/Entity/User.php
  src/Twig/Components/UpdateStateFavoriteRecipeComponent.php
  templates/components/UpdateStateFavoriteRecipeComponent.html.twig
  templates/recipe/index.html.twig
Labels: REVIEWED

#100 User quiz
  assets/styles/quiz.scss
  composer.json
  composer.lock
  migrations/Version20230705140714.php
  src/Controller/RegistrationController.php
  src/Controller/SessionController.php
  src/Controller/UserQuizController.php
  src/Entity/User.php
  src/Entity/UserPreference.php
  src/Form/QuizIntroductionType.php
  src/Repository/UserPreferenceRepository.php
  src/Twig/Components/RegistrationForm.php
  templates/admin/session/sessions_states.html.twig
  templates/registration/register.html.twig
  templates/user_quiz/knowledge.html.twig
  webpack.config.js
Labels: CONFLICTS RESOLVED, REVIEWED

#114 fix relation wine tastingSheet
  src/Entity/Wine.php
Labels: REVIEWED

#113 component enable for wine
  src/Entity/Wine.php
  src/Twig/Components/EnableDesableWineComponent.php
  templates/admin/grape_variety/index.html.twig
  templates/admin/wine/_form.html.twig
  templates/admin/wine/index.html.twig
  templates/components/EnableDesableWineComponent.html.twig
Labels: REVIEWED

#116 User quiz recap
  src/Controller/UserQuizController.php
  src/Form/QuizIntroductionType.php
  templates/user_quiz/recap.html.twig
Labels: REVIEWED

#118 livraison premiere version
  assets/controllers.json
  assets/styles/wine.scss
  composer.json
  composer.lock
  config/bundles.php
  config/routes/ux_autocomplete.yaml
  package.json
  src/Form/Search/GrapeVarietiesAutocompleteField.php
  src/Form/Search/SearchWineDataFormType.php
  src/Repository/WineRepository.php
  src/Search/SearchWineData.php
  symfony.lock
  yarn.lock
Labels: REVIEWED

#117 dev to main
  assets/controllers.json
  assets/styles/wine.scss
  composer.json
  composer.lock
  config/bundles.php
  config/routes/ux_autocomplete.yaml
  package.json
  src/Controller/UserQuizController.php
  src/Entity/Wine.php
  src/Form/QuizIntroductionType.php
  src/Form/Search/GrapeVarietiesAutocompleteField.php
  src/Form/Search/SearchWineDataFormType.php
  src/Repository/WineRepository.php
  src/Search/SearchWineData.php
  src/Twig/Components/EnableDesableWineComponent.php
  symfony.lock
  templates/admin/grape_variety/index.html.twig
  templates/admin/wine/_form.html.twig
  templates/admin/wine/index.html.twig
  templates/components/EnableDesableWineComponent.html.twig
  templates/user_quiz/recap.html.twig
  yarn.lock
Labels: REVIEWED

#119 fixe css session
  assets/images/wine.svg
  assets/styles/_variables.scss
  assets/styles/app.scss
  assets/styles/session.scss
  templates/components/session/_card_session.html.twig
  templates/components/session/_card_session_grape_variety.html.twig
  templates/components/session/_next_sessions.html.twig
  templates/components/session/_opened_sessions.html.twig
Labels: REVIEWED

#110 S05 us24 service dosage
  src/Controller/TastingSheetController.php
  src/Service/CalculateWineDosageService.php
  tests/CalculateWineDosageServiceTest.php
Labels: REVIEWED

#120 refonte search bar wine
  assets/styles/wine.scss
  src/Form/Search/SearchWineDataFormType.php
  templates/admin/grape_variety/_form.html.twig
  templates/components/search/_searchWinFormData.html.twig
Labels: REVIEWED

#122 fix bug service
  src/Controller/TastingSheetController.php
Labels: REVIEWED

#124 S06 us62 profile
  assets/styles/_variables.scss
  assets/styles/profile.scss
  src/Controller/RecipeController.php
  src/Controller/UserController.php
  src/Controller/admin/AdminUserController.php
  src/Form/UserType.php
  templates/admin/user/_form.html.twig
  templates/admin/user/edit.html.twig
  templates/components/_navbar.html.twig
  templates/components/svg/_icon_profile_user.svg.twig
  templates/recipe/index.html.twig
  templates/user_profile/_profileForm.html.twig
  templates/user_profile/userProfile.html.twig
  webpack.config.js
Labels: REVIEWED

#126 add send email and enable desable members admin
  assets/styles/app.scss
  assets/styles/resetPassword.scss
  config/packages/security.yaml
  migrations/Version20230710080735.php
  src/Controller/LoginController.php
  src/Controller/UserController.php
  src/Entity/User.php
  src/Security/UserChecker.php
  src/Twig/Components/EnableDesableUserComponent.php
  templates/admin/components/_admin-navbar.html.twig
  templates/admin/user/index.html.twig
  templates/components/EnableDesableUserComponent.html.twig
  templates/components/_navbar.html.twig
  templates/login/index.html.twig
  templates/user_profile/email.html.twig
  templates/user_profile/userProfile.html.twig
Labels: REVIEWED

#127 fixe css
  assets/styles/_variables.scss
  assets/styles/admin.scss
  templates/admin/grape_variety/index.html.twig
  templates/admin/session/index.html.twig
  templates/admin/wine/index.html.twig
  templates/components/EnableDesableUserComponent.html.twig
  templates/components/EnableDesableWineComponent.html.twig
  templates/recipe/recipeResult.html.twig
Labels: REVIEWED

#123 recipe index
  assets/styles/recipe.scss
  composer.lock
  src/Controller/RecipeController.php
  src/DataFixtures/RecipeFixtures.php
  src/DataFixtures/TastingSheetFixtures.php
  templates/components/_navbar.html.twig
  templates/recipe/index.html.twig
  templates/recipe/recipeResult.html.twig
  templates/recipe/resultat.html.twig
Labels: REVIEWED

#129 created wine taste table and implemented it
  migrations/Version20230710135306.php
  migrations/Version20230710144913.php
  src/DataFixtures/WineTasteFixtures.php
  src/Entity/UserPreference.php
  src/Entity/WineTaste.php
  src/Form/QuizIntroductionType.php
  src/Form/WineType.php
  src/Repository/WineTasteRepository.php
  templates/user_quiz/knowledge.html.twig
  templates/user_quiz/recap.html.twig
Labels: CORRECTIONS DONE, REVIEWED

#131 recipe user
  assets/styles/recipe.scss
  src/Controller/RecipeController.php
  templates/components/_navbar.html.twig
  templates/recipe/index.html.twig
  templates/recipe/recipeUser.html.twig
Labels: REVIEWED

#133 final recipe
  src/Controller/RecipeController.php
  templates/recipe/finalRecipe.html.twig
Labels: REVIEWED

#130 add rangebar edit recipe
  assets/styles/app.scss
  assets/styles/recipe.scss
  assets/styles/tastingSheet.scss
  src/Controller/RecipeController.php
  src/Form/FinalRecipeType.php
  src/Form/RecipeDosageType.php
  templates/recipe/resultat.html.twig
  templates/tasting_sheet/resultTastingSheet.html.twig
Labels: CONFLICTS RESOLVED, REVIEWED

#136 S06 us65 recipe show
  src/Controller/RecipeController.php
  templates/recipe/index.html.twig
  templates/recipe/recipeUser.html.twig
  templates/recipe/show.html.twig
Labels: CONFLICTS RESOLVED, REVIEWED

#132 add a before button
  assets/tastingSheet.js
  composer.json
  composer.lock
  templates/tasting_sheet/index.html.twig
Labels: REVIEWED

#137 fix suppression component favoris recipe
  templates/recipe/finalRecipe.html.twig
  templates/recipe/index.html.twig
  templates/recipe/show.html.twig
Labels: REVIEWED

#138 fixe css and responsive tasting sheet
  assets/styles/app.scss
  assets/styles/recipe.scss
  assets/styles/tastingSheet.scss
  src/Form/TastingSheetType.php
  templates/tasting_sheet/index.html.twig
Labels: REVIEWED

#139 fixe moyenne round
  templates/tasting_sheet/resultTastingSheet.html.twig
Labels: REVIEWED

#141 Fixe recipe index
  assets/styles/recipe.scss
  templates/recipe/index.html.twig
Labels: REVIEWED

#140 fixe final recipe
  assets/recipeTimer.js
  assets/styles/app.scss
  assets/styles/profile.scss
  src/Controller/RecipeController.php
  templates/recipe/resultat.html.twig
  webpack.config.js
Labels: CONFLICTS RESOLVED, CORRECTIONS DONE, REVIEWED

#142 fixe secure recipe
  src/Controller/RecipeController.php
Labels: REVIEWED

#146 finished wineRegion part and quiz section
  migrations/Version20230712084411.php
  migrations/Version20230717081824.php
  src/DataFixtures/WineRegionFixtures.php
  src/DataFixtures/WineTasteFixtures.php
  src/Entity/UserPreference.php
  src/Entity/WineRegion.php
  src/Form/QuizIntroductionType.php
  src/Form/WineType.php
  src/Repository/WineRegionRepository.php
  templates/user_quiz/recap.html.twig
Labels: REVIEWED

#147 fix path add session
  templates/admin/session/index.html.twig
Labels: REVIEWED

#148 fix
  src/Controller/RecipeController.php
Labels: REVIEWED

#150 add fix winetype
  src/Form/WineType.php
Labels: REVIEWED

#151 made restriction for being able to answer the quiz only once on sign up
  migrations/Version20230717085005.php
  src/Controller/RegistrationController.php
  src/Controller/UserQuizController.php
  src/Entity/User.php
  templates/user_quiz/recap.html.twig
Labels: REVIEWED

#153 joined wineRegion and wineTaste to Wine class
  migrations/Version20230717094536.php
  src/Controller/admin/AdminWineController.php
  src/DataFixtures/WineFixtures.php
  src/Entity/Wine.php
  src/Entity/WineRegion.php
  src/Entity/WineTaste.php
  src/Form/WineType.php
  templates/admin/wine/index.html.twig
Labels: REVIEWED

#154 fixe all lines pages
  assets/styles/_variables.scss
  assets/styles/app.scss
  assets/styles/home.scss
  templates/components/session/_next_sessions.html.twig
  templates/components/session/_opened_sessions.html.twig
  templates/components/svg/_frame_surlignage_main.svg.twig
  templates/home/index.html.twig
  templates/recipe/index.html.twig
  templates/recipe/resultat.html.twig
  templates/tasting_sheet/index.html.twig
  templates/tasting_sheet/resultTastingSheet.html.twig
  templates/wine/index.html.twig
Labels: REVIEWED

#152 Add champ recipe name
  .github/workflows/main.yml
  assets/recipeTimer.js
  assets/styles/recipe.scss
  src/Controller/RecipeController.php
  src/DataFixtures/TastingSheetFixtures.php
  src/Entity/TastingSheet.php
  src/Form/FinalRecipeType.php
  src/Service/CalculateFinalDosageService.php
  src/Service/CalculateWineDosageService.php
  templates/recipe/finalRecipe.html.twig
  templates/recipe/resultat.html.twig
  webpack.config.js
Labels: AWAITING TEAM REVIEW

#155 missing closed div
  templates/admin/wine/edit.html.twig
Labels: REVIEWED

#180 add favorite recipep age
  src/Controller/RecipeController.php
  templates/components/_navbar.html.twig
  templates/recipe/favoritesRecipes.html.twig
Labels: REVIEWED

#181 fixe registration redirection
  src/Controller/RegistrationController.php
  templates/registration/confirmation_registration.html.twig
Labels: REVIEWED

#184 save JA eyes
  assets/styles/app.scss
Labels: REVIEWED

#182 fixe footer
  src/Controller/MentionsController.php
  templates/components/_footer.html.twig
  templates/components/_mentions.html.twig
Labels: REVIEWED

#186 fixe errors message register
  src/Entity/User.php
Labels: REVIEWED

#187 fixe session admin
  src/Form/SessionType.php
  templates/admin/session/_form.html.twig
Labels: REVIEWED

#188 fixe admin recipe
  templates/admin/admin_recipe/_form.html.twig
  templates/admin/admin_recipe/edit.html.twig
  templates/admin/admin_recipe/index.html.twig
Labels: REVIEWED

#189 fixe home page
  assets/styles/_variables.scss
  src/Controller/RegistrationController.php
  templates/home/index.html.twig
Labels: REVIEWED

#183 fix show recipe
  templates/recipe/show.html.twig
Labels: CONFLICTS RESOLVED, REVIEWED

#191 fixe all titles
  assets/styles/app.scss
  assets/styles/home.scss
  templates/components/session/_next_sessions.html.twig
  templates/components/session/_opened_sessions.html.twig
  templates/home/index.html.twig
  templates/recipe/favoritesRecipes.html.twig
  templates/recipe/finalRecipe.html.twig
  templates/recipe/index.html.twig
  templates/recipe/resultat.html.twig
  templates/recipe/show.html.twig
  templates/tasting_sheet/index.html.twig
  templates/tasting_sheet/resultTastingSheet.html.twig
  templates/wine/index.html.twig
Labels: CONFLICTS RESOLVED, REVIEWED

#192 fixe css recipe show
  assets/styles/app.scss
  assets/styles/recipe.scss
  templates/recipe/show.html.twig
Labels: CONFLICTS RESOLVED, REVIEWED

#193 add shadows
  templates/contact/contact.html.twig
  templates/registration/register.html.twig
  templates/tasting_sheet/index.html.twig
  templates/tasting_sheet/resultTastingSheet.html.twig
Labels: REVIEWED

#195 fix the as Sylvain wanted
  assets/styles/app.scss
  assets/styles/contactForm.scss
  templates/contact/contact.html.twig
Labels: CONFLICTS RESOLVED, REVIEWED

#197 fixe css session
  assets/styles/session.scss
  templates/admin/session/sessions_states.html.twig
  templates/components/session/_card_session.html.twig
  templates/components/session/_card_session_grape_variety.html.twig
  templates/components/session/_opened_sessions.html.twig
  templates/components/svg/_icon_location.svg.twig
  templates/recipe/favoritesRecipes.html.twig
Labels: REVIEWED

#198 change body
  assets/styles/home.scss
Labels: REVIEWED

#213 fix folder admin_recipe
  src/Controller/admin/AdminRecipeController.php
  templates/admin/recipe/_delete_form.html.twig
  templates/admin/recipe/_form.html.twig
  templates/admin/recipe/edit.html.twig
  templates/admin/recipe/index.html.twig
Labels: REVIEWED

#214 favoriteWinePageDone
  src/Controller/WineController.php
  templates/components/_navbar.html.twig
  templates/wine/favoritesWines.html.twig
Labels: REVIEWED

#215 if nothing in db
  templates/recipe/index.html.twig
  templates/wine/index.html.twig
Labels: REVIEWED

#216 fix delete button on session
  src/Entity/Session.php
  templates/admin/session/index.html.twig
Labels: REVIEWED

#217 fix user admin
  src/Controller/admin/AdminUserController.php
  templates/admin/user/_form.html.twig
  templates/admin/user/index.html.twig
  templates/admin/user/new.html.twig
  templates/admin/user/show.html.twig
Labels: REVIEWED

#218 remove cepage description
  migrations/Version20230721095620.php
  src/DataFixtures/GrapeVarietyFixtures.php
  src/Entity/GrapeVariety.php
  src/Form/GrapeVarietyType.php
  templates/admin/grape_variety/new.html.twig
Labels: REVIEWED

#220 nextandbeforebuttonsomejs
  assets/tastingSheet.js
  templates/tasting_sheet/index.html.twig
Labels: REVIEWED

#219 add message if seance is empty
  templates/components/session/_next_sessions.html.twig
Labels: CORRECTIONS DONE, REVIEWED

#221 add assert to wine entity
  src/Entity/Wine.php
Labels: REVIEWED

#222 add show recipe as admin and remove delete and edit
  src/Controller/admin/AdminRecipeController.php
  templates/admin.html.twig
  templates/admin/recipe/index.html.twig
  templates/admin/recipe/show.html.twig
  templates/recipe/show.html.twig
Labels: REVIEWED

#223 remove button add user
  templates/admin/user/index.html.twig
Labels: REVIEWED

#224 add user preference in profile
  assets/fonts/Fontspring-DEMO-theseasons-reg.otf
  assets/styles/_fonts.scss
  assets/styles/_variables.scss
  assets/styles/app.scss
  assets/styles/recipe.scss
  templates/user_profile/userProfile.html.twig
Labels: REVIEWED

#225 fixturedone
  src/DataFixtures/UserFixtures.php
  src/DataFixtures/UserPreferenceFixtures.php
Labels: REVIEWED

#226 fixNavBar if connected or not dropdown and all
  templates/components/_navbar.html.twig
Labels: REVIEWED

#227 fix path
  templates/recipe/show.html.twig
Labels: REVIEWED

#228 fixed and added assertion for session opening date
  src/Entity/Session.php
Labels: REVIEWED

#232 added modal list to display session subscribed users
  templates/admin/session/index.html.twig
Labels: REVIEWED

#229 Fixe footer css
  assets/tastingSheet.js
  templates/tasting_sheet/index.html.twig
Labels: REVIEWED

#233 S
  templates/components/session/_next_sessions.html.twig
Labels: REVIEWED

#236 home page padding
  templates/home/index.html.twig
Labels: REVIEWED

#234 add caclulate sum of ML on slide range
  assets/rangeAnimation.js
  src/Controller/RecipeController.php
  templates/recipe/resultat.html.twig
  templates/tasting_sheet/index.html.twig
  webpack.config.js
Labels: REVIEWED

#239 add wine show
  assets/styles/wine.scss
  src/Controller/WineController.php
  templates/components/UpdateStateFavoriteWineComponent.html.twig
  templates/components/session/_card_session_grape_variety.html.twig
  templates/wine/show.html.twig
Labels: CONFLICTS RESOLVED, REVIEWED

#243 fixe header
  templates/components/_navbar.html.twig
  templates/home/index.html.twig
Labels: REVIEWED

#250 add show wine
  src/Twig/Components/UpdateStateFavoriteRecipeComponent.php
  src/Twig/Components/UpdateStateFavoriteWineComponent.php
  templates/components/UpdateStateFavoriteRecipeComponent.html.twig
  templates/components/UpdateStateFavoriteWineComponent.html.twig
  templates/wine/index.html.twig
Labels: REVIEWED

#252 fix wine like no value
  templates/components/UpdateStateLikeRecipeComponent.html.twig
Labels: REVIEWED, AWAITING TEAM REVIEW

#256 fix register letter and number
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  templates/components/RegistrationForm.html.twig
Labels: REVIEWED

#257 fixe wines
  assets/styles/wine.scss
  src/Controller/WineController.php
  src/Form/Search/SearchWineDataFormType.php
  templates/components/_navbar.html.twig
  templates/components/search/_searchWinFormData.html.twig
  templates/wine/favoritesWines.html.twig
  templates/wine/index.html.twig
Labels: REVIEWED

#259 fixe size wine
  templates/wine/show.html.twig
Labels: REVIEWED

#261 fixed fixtures age
  src/DataFixtures/UserFixtures.php
Labels: REVIEWED

#262 add quizz redirection after login
  config/packages/security.yaml
  src/Controller/UserQuizController.php
Labels: REVIEWED

#260 fix country
  composer.json
  composer.lock
  src/DataFixtures/UserFixtures.php
  src/Form/RegistrationFormType.php
  src/Form/UserType.php
  templates/admin/user/show.html.twig
  templates/components/RegistrationForm.html.twig
Labels: REVIEWED

#263 fixed syntax on homepage text
  templates/home/index.html.twig
Labels: REVIEWED

#264 fix framework.yaml
  config/packages/framework.yaml
Labels: REVIEWED

#266 fixe quiz margin
  templates/user_profile/userProfile.html.twig
  templates/user_quiz/knowledge.html.twig
  templates/user_quiz/recap.html.twig
Labels: REVIEWED

#267 dev to main
  composer.json
  composer.lock
  config/packages/framework.yaml
  config/packages/security.yaml
  src/Controller/UserQuizController.php
  src/DataFixtures/UserFixtures.php
  src/Form/RegistrationFormType.php
  src/Form/UserType.php
  templates/admin/user/show.html.twig
  templates/components/RegistrationForm.html.twig
  templates/home/index.html.twig
  templates/user_profile/userProfile.html.twig
  templates/user_quiz/knowledge.html.twig
  templates/user_quiz/recap.html.twig
  templates/wine/show.html.twig
Labels: REVIEWED
